### ISSUE TITLE
Moved Permanently

### ISSUE THREAD

**Issue by dikaio** [stephenlb/pubnub-mongo-pipe#1]
It looks like this link is no longer working. Is there an updated url?

http://goo.gl/bUlUh

**Comment by stephenlb** [comment]
the "DEMO" key is throttled now.  you may need to add your own keys.

On Wed, Dec 3, 2014 at 7:39 AM, Don Dikaio notifications@github.com wrote:

> It looks like this link is no longer working. Is there an updated url?
> 
> http://goo.gl/bUlUh
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stephenlb/pubnub-mongo-pipe/issues/1.

## 

Cheers!
Stephen Blum - CTO PubNub
http://twitter.com/stephenlb
https://github.com/pubnub - GitHub
www.pubnub.com
+1-425-830-6711
